[build]
  base = "."
  command = "cd frontend && npm install && npm run build:production && cd ../netlify/functions && npm install"
  publish = "frontend/dist"

[functions]
  directory = "netlify/functions"
  included_files = [
    "netlify/functions/sprouter_events.db",
    "netlify/functions/volunteer-codes.json",
    "netlify/functions/sessions.json"
  ]

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  VITE_APP_ENV = "production"
  VITE_APP_URL = "https://maidutickets.com"
  VITE_API_URL = "https://maidutickets.com"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  NPM_CONFIG_ENGINE_STRICT = "false"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_LOGLEVEL = "error"

# API redirects to Netlify Functions
[[redirects]]
  from = "/api/auth"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/analytics"
  to = "/.netlify/functions/analytics"
  status = 200

[[redirects]]
  from = "/api/track-event"
  to = "/.netlify/functions/api/track-event"
  status = 200

[[redirects]]
  from = "/api/track-activity"
  to = "/.netlify/functions/api/track-activity"
  status = 200

[[redirects]]
  from = "/api/track-session"
  to = "/.netlify/functions/api/track-session"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
