[build]
  base = "."
  command = "cd frontend && npm install --legacy-peer-deps && npm run build:production && cd ../netlify/functions && npm install"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  VITE_APP_ENV = "production"
  VITE_APP_URL = "https://maidutickets.com"
  VITE_API_URL = "https://maidutickets.com"
  JWT_SECRET = "86d2bbcb5cd6a7b84f1e84473a95c976fd1febc5955da91779765d8df109304812e3c2b6410eb4c92cfa524f17e0263649f3b164297c0c94dcc0798682f1c8fe"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  NPM_CONFIG_ENGINE_STRICT = "false"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_LOGLEVEL = "error"

# Handle client-side routing for React SPA
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-production"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
