[build]
  command = "npm --prefix frontend install && npm --prefix frontend run build:production"
  publish = "frontend/dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200