[build]
  base = "frontend"
  command = "yarn build:production"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  VITE_APP_ENV = "production"

# Handle client-side routing for React SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
