[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps && npm run build:production"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  VITE_APP_ENV = "production"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  NPM_CONFIG_ENGINE_STRICT = "false"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_LOGLEVEL = "error"

# Handle client-side routing for React SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
