[build]
  base = "frontend"
  command = "yarn install --frozen-lockfile && yarn build"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  VITE_APP_ENV = "production"
  YARN_VERSION = "1.22.22"

# Handle client-side routing for React SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
