[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps && npm run build:production"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  VITE_APP_ENV = "production"
  VITE_APP_URL = "https://maidutickets.com"
  VITE_API_URL = "https://maidutickets.com"
  JWT_SECRET = "86d2bbcb5cd6a7b84f1e84473a95c976fd1febc5955da91779765d8df109304812e3c2b6410eb4c92cfa524f17e0263649f3b164297c0c94dcc0798682f1c8fe"
  ANALYTICS_ENCRYPTION_KEY = "276970bfb90ec83a75fbd70a1685557a297b31f4586f6b8e098c81511b7a0bef"
  ADMIN_CODE = "ADMIN2024"
  DATABASE_PATH = "netlify/functions/sprouter_events.db"
  SESSION_STORAGE_PATH = "data/sessions.json"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  NPM_CONFIG_ENGINE_STRICT = "false"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_LOGLEVEL = "error"

# Function timeout and configuration
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sqlite3"]
  timeout = 30

# API redirects - MUST come before catch-all redirect
[[redirects]]
  from = "/api/auth"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/analytics"
  to = "/.netlify/functions/analytics"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

# Domain-specific redirects
[[redirects]]
  from = "https://www.maidutickets.com/*"
  to = "https://maidutickets.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.sproutersecure.com/*"
  to = "https://sproutersecure.com/:splat"
  status = 301
  force = true

# SPA catch-all redirect - MUST be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
